### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by alexandre-butynski** [LaravelCollective/html#158]
Is this package compatible with PHP 7 ? This version is becoming the new standard and Laravel 5.1+ is compatible.

Can we add this version of PHP in the travis build configuration ?

**Comment by parabol** [comment]
i experienced fatal errors.
i work on php7@homestead vagrant box.

`{!! Form::$setting['macro']("form[".$group."][".$setting['key']."]",$defaultValue,['class' => 'form-control'.($errors->has("form[".$group."][".$setting['key']."]") ? ' focus' : '')]) !!}`


so it get an error ;

`Fatal error: Access to undeclared static property: Collective\Html\FormFacade::$setting`


it works flawlessly on php5.6..

i am not sure if it is related php7 or else..

**Comment by rafael-renan-pacheco** [comment]
It is related with php7, as you can see here http://php.net/manual/en/migration70.incompatible.php in **Old and new evaluation of indirect expressions**.

But this is not a problem related with LaravelCollective/html, because we are using it with php 7 with no errors at all. The problem is that you are using a sintax that has been changed the way it works.

**Comment by parabol** [comment]
Hi,
i fixed the syntax from:

`{!! Form::$setting['macro']("form...`

to:

`{!! Form::{$setting['macro']}("form...`

now it works on both side (php5.6 and php7.x) 

so it was my bad.

i will report if i detect any bug/error with Php7.x 

thank you for your help Rafael
