### ISSUE TITLE
Priority

### ISSUE THREAD

**Issue by ionesculiviucristian** [LaravelCollective/html#295]
```php
public function getValueAttribute($name, $value = null)
    {
        if (is_null($name)) {
            return $value;
        }

        if (! is_null($this->old($name))) {
            return $this->old($name);
        }

        if (! is_null($value)) {
            return $value;
        }

        if (isset($this->model)) {
            return $this->getModelValueAttribute($name);
        }
    }
```

Why does old values have priority over directly assign values ?

**Comment by garygreen** [comment]
This is has discussed a number of times and imo is correct. Old values should take priority because if your redirecting back to the form with errors, it should use the old values the user was originally trying to save, otherwise you'd overwrite them with whatever is on the model or value supplied to the element.
