### ISSUE TITLE
Website SSL cert expired

### ISSUE THREAD

**Issue by rawzone** [LaravelCollective/html#308]
Seems like the SSL cert for https://laravelcollective.com has expired. Time to hit that Letsencrypt script (And setup a cron job).

**Comment by adamgoose** [comment]
Thanks! Close

Thanks,

Adam.

--

Adam Engebretson

Sent from
https://polymail.io/

On Sun, Mar 19, 2017 at 7:18 AM Hans Nielsen

<
mailto:Hans Nielsen <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Seems like the SSL cert for
https://laravelcollective.com
has expired. Time to hit that Letsencrypt script (And setup a cron job).

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/LaravelCollective/html/issues/308
, or
