### ISSUE TITLE
5.4.1 -> 5.4.3 breaks nested form model attributes

### ISSUE THREAD

**Issue by karlshea** [LaravelCollective/html#329]
`Form::textarea("NoteInformation[0][Note]")` works in 5.4.1 but breaks in 5.4.3.

In FormBuilder's getModelValueAttribute(), $key is transformed to "NoteInformation.0.Note". This works for the first level, so I can get "NoteInformation" (returns array), and "NoteInformation[0]" (returns first element of array), but then getModelValueAttribute() is called recursively with the key "0.Note", and *that* key is transformed to "0_Note" which fails the nested value check and NULL is returned. 

It looks like this was introduced in 752951e. I'm not totally sure what was trying to get accomplished there so I'm not sure what changes would need to be made.

**Comment by karlshea** [comment]
Related to #314

**Comment by rjvandoesburg** [comment]
Noticed the same thing after updating just now, quite a bit change for a minor number, have to revert back for now as we are using the nested thing a lot and updating all references would take some time :(

**Comment by mlantz** [comment]
Fix is on the way - sorry about this

**Comment by mlantz** [comment]
The root of the problem was that the nested ignored formAttributes which meant that with nested models you would miss out on the formattribute components. I've reverted portions of the code to get back the 'normal' nesting - but now have it able to detect if the nested components are in fact models with their own formAttribute methods. I'm just confirming a few more things before I release today. Thanks for reporting.

**Comment by rjvandoesburg** [comment]
Had a bad day at work, reading the comment again I could have framed it better, sorry if it seemed negative. Thanks for the quick replies :)

**Comment by mlantz** [comment]
No worries, I'm trying to fix things up and address some of the concerns that have lingered for a while to make things more efficient.
