### ISSUE TITLE
Old value for select is not being set

### ISSUE THREAD

**Issue by santigarcor** [LaravelCollective/html#345]
I'm using larave 5.4 and laravelcollective 5.4, and when i create a select (multiple), if the data doesn't pass the validation, the old selected values are not being set, i tracked the problem to the `getSelectedValue` method because it's using the `in_array` in strict mode. The problem is that the data from the session is being retrieved as a string and the value being searched is an integer.

In this screeshot you can se that the first dump is an integer (it's the `$value` parameter) and the second one is an array with a string inside (it's the $selected parameter):

![image](https://cloud.githubusercontent.com/assets/7565417/26331870/f2abd51e-3f18-11e7-9cdc-5e61b3d0c54b.png)

**Comment by jaminscript** [comment]
Removing strict mode worked for me. Who knew opening cans of worms was so easy?

**Comment by abixalmon** [comment]
Same issue here!

```
{!! Form::select('language[]', $languages, request()->get('language'), ['class' => 'form-control', 'multiple'=>'multiple', 'style'=>'width: 100%;']) !!}
```

Doesn't get selected

**Comment by unamix** [comment]
Same issue here with multi select in v5.2.6.
Selected items are not being set.

**Comment by glaubersp** [comment]
Hi guys. I'm facing similar issue here.
I have
`{{ Form::select('topic_tags[]', $topic_tags, $agreement->topicTags->pluck('id')->all(), ['class' => 'form-control','multiple' => 'multiple']) }}`
inside a
`{!! Form::model($agreement, [ 'method' =>'PATCH', 'route' => ['frontend.ceap.agreements.update', $agreement->id]]) !!}`

First time I open this view, `$agreement->topicTags->pluck('id')->all()` is able to correctly set the values for the select because it returns an array of int. 

When a validation fails, what I realised is that `old('topic_tags')` returns an array of STRINGS and then the line 
`return in_array($value, $selected, true) ? 'selected' : null;`
 inside `FormBuilder::getSelectedValue()` is not able to correctly return the selected values because the third parameter asks the types of both values being tested to appear inside the array and the array items to be checked for equality.

Will anyone confirm the array after validation contains strings in place of ints?
Does anyone know why this happens?
I think validation failure should return an array of ints, but I could not find where this type change occurs yet.

**Comment by MaikelKnight1984** [comment]
Same issue here! I think, the strict parameter inside FormBuilder::getSelectedValue() is correct, because of "1" is different to 1. My opinion ist, that the real change should be in FormBuilder "getValueAttribute" on lines 1163-1170.
```
$request = $this->request($name);
if (!is_null($request)) {
      return $request;
}

if (! is_null($value)) {
    return $value;
}
```

This is the place, where the given values are overwritten by request parameters. In this place, the better behaviour should look like.

```
if (! is_null($value)) {
    return $value;
}

$request = $this->request($name);
if (!is_null($request)) {
      return $request;
}
```

My opinion is, that if i set an value to the select option, this option should have a higher priority than the request values.

For your interest. If array keys set as string, for example "1", PHP casts those to integers.

**Comment by david-ridgeonnet** [comment]
@MaikelKnight1984 I think you're missing the point. For example, if we have select option:

```
Form::select('field', [1 => 'one', 2 => 'two', 3 => 'three'])
```

And we submit form with `2` selected, but the form fails and it redirects back with the input, the `old('field')` input for the select is `"2"` (the request is not aware whether data should be numeric, string, boolean etc.).

The option is then not selected correctly due to the strict comparison (as we know, `"2"` does not match `2` when using strict comparison).

**Comment by MaikelKnight1984** [comment]
@david-ridgeonnet Yes, you are right. 

Thumb up for changing strict to default false in ```FormBuilder::getSelectedValue()```. :)

Nevertheless, own given values should have a higher priority than the request. But this should be another issue. ;)

**Comment by dbpolito** [comment]
I'm having problems because of https://github.com/LaravelCollective/html/issues/345#issuecomment-306855529 too.

Request param getting preference than the default value i provide...

**Comment by ajoy39** [comment]
Same issue here. We're reverting to 5.1 for now.

**Comment by BadChoice** [comment]
Same here, is there any way to make it work again?

**Comment by robertravnik** [comment]
I can also confirm this issue. Laravel's old() returns values as strings, while select() requires integer values. Setting in_array strict checking in `FormBuilder`'s `getSelectedValue($value, $selected)` to `false `resolved this.

**Comment by piperone** [comment]
This is the offending PR originally:  #127 
Subsequent commit: f620ae4
Dupe PR: #368 
Relevant issue: #374

**Comment by tshafer** [comment]
Is this still an issue?

**Comment by tshafer** [comment]
Closed due to inactivity.

**Comment by ffogarasi** [comment]
I found a workaround for this:
Set the name of the select to **_null_** and add the name in the **_selectAttributes_**:
Example:
Form::select(null, $items, old('list_items')), [ 'name' => 'list_items[]',  'multiple' => 'multiple'])
