### ISSUE TITLE
Form::hidden() should not use old() to set value

### ISSUE THREAD

**Issue by common-link-dev** [LaravelCollective/html#350]
Hi,

when adding a checkbox it is nice to add a hidden field with the same name to send a default value to the controller, if the checkbox is not checked. 

If the checkbox was checked o form submit and the user is redirected back to the form and the old input is applied to the form, the hidden field value gets overwritten with the checkbox value.

Example:
`{{ Form::hidden('cb_name', '0') }}
{{ Form::checkbox('cb_name', '1') }}`

After the redirect with previously checked checkbox "cb_name" the value of the hidden field changes to the value of the checkbox. That means, that if the user unchecks the checkbox, the checkbox value is still sent to the controller with the next submit.

I thin the reason is in FormBuilder::getValueAttribute() method. It uses $this->old() to set the previous value, but in case of hidden fields I think this behaviour is unwanted.

Best Wishes
David

**Comment by MarnuLombard** [comment]
In fact, no `Form::input()` should override what is provided as the `$value`, which it does as of the 5.4 release.
If I pass in a value of `foobarbaz`, why is it overridden by first `old()` and then `request()->input()`?

**Comment by david-ridgeonnet** [comment]
@MarnuLombard If you're providing a value to `Form::input`, it *should* be overwritten by the old otherwise when you redirect back any changes the user/visitor did are lost. Pretty sure that's always been how it has worked.

**Comment by MarnuLombard** [comment]
@david-ridgeonnet If I provide a static value, or wish to have the input always be reset to null - it should do that IMO.
It certainly always used to do that, ie. allow for null/falsey values to be accepted as a valid default/override

**Comment by david-ridgeonnet** [comment]
@MarnuLombard as far as I can remember it's always used the `old` input over the value provided (as any errors that occur, a sensible user experience is to redirect back and present the form with the information they proved, not having to type it out all again). See the original library https://github.com/illuminate/html/blob/master/FormBuilder.php which also contains the `old` value being preferred over the value provided.

May I suggest you either do not redirect with the input (if you're not going to use the "old" input, no point in keeping it)?

If we don't allow `old` to be preferred, then that would mean everywhere we want to display the `old` data we'd have to use the `old` method.

**Comment by common-link-dev** [comment]
You could also use $request->only() or $request->except() when redirecting back with input to ignore specific user input.

**Comment by wyred** [comment]
There is a problem when form arrays are involved.

    @for ($x = 0; $x < 4; $x++)
        {!! Form::hidden('ages[]', $ages[$x]) !!}
    @endfor

**Comment by ataboo** [comment]
Sometimes the `old()` flashed data is overwriting the hidden `_method` field in our generated forms with old data (DELETE to POST, etc.).

Also some hardcoded hidden fields are being changed by other fields of the same name.
For example a hidden field paired with a checkbox to provide a false value now gets changed with the checkbox's value.

This broke for us sometime between 5.4.1 and 5.4.8, and the old behavior allowed us to flash the old session for relevant behavior without any hardcoded values being changed.  

We tried fixing most cases by adding the html instead of the `Form::hidden` helper but it kept popping up so we've had to role back to 5.4.1.

**Comment by wyred** [comment]
I realized that a simple workaround is to just write plain HTML.

    @for ($x = 0; $x < 4; $x++)
        <input type="hidden" name="ages[]" value="{{ $ages[$x] }}">
    @endfor

But in case I'm missing out something, is there a good reason we should be using `Form::hidden()` instead of writing plain HTML?

**Comment by tshafer** [comment]
Is this still an issue?

**Comment by smilearric** [comment]
Hi,

The changes from 5.4.1 to 5.4.9 break our multi-step form since the step number we passed to the view on the store method which is called between each step is no longer reflecting its real value within the hidden form.

The controller:
```
    /**
     * @param Request $request
     */
    public function store(Request $request)
    {
//...
            $params['step'] = $next_step; // 2
//...
            return view('form.edit_step_by_step', $params);
    }
```

The view:
```
            <form method="POST" action={{ route('form.store') }}>
                {{ csrf_field() }}
                {{ Form::hidden('step', $step) }} // Should be 2 (as of v5.4.1) but remains at 1 with v5.4.9.
                {{ $step }} // 2
```

The route:
```
    Route::resource('/form', 'TheController', ['except' => ['destroy', 'edit', 'show']]);
```

We have around 50 hidden fileds occurrences spread over the app.

Since we want to upgrade to Laravel 5.6 (and therefore Collective>5.4.9) but we do not know precisely what drawbacks this commits will have on our app, the Form::hidden() method is becoming an "anti-feature" for us.

We are facing hardcoding plain old HTML for each of the hidden fields which we would like to avoid... We'd prefer to stick with native Laravel handling of hidden forms. What can we do?

Please tell us whether and what we've done wrong or you may consider not using old() anymore as a regression.

Thank you

**Comment by david-ridgeonnet** [comment]
How are you going to the next step, are you redirecting "withInput"?

**Comment by smilearric** [comment]
Like so, on submit:

```
    public function store(Request $request)
    {
//...
            $params['step'] = $next_step; // 2
//...
            return view('form.edit_step_by_step', $params);
    }
```

We are not redirecting "withInput". Do you suggest we do so? We want to store the values between each step. Will this still be possible this way?

**Comment by drn5910** [comment]
How are you getting to the store function? If you were submitting a form that goes directly there, then the `old('step')` shouldn't even be populated. It would only be populated on a response/redirect with input.

**Comment by smilearric** [comment]
Yes, we are submitting directly here. We load a different partial on each step, wich is okay.

You may surely be right in that it might not be a problem related to old(). With 5.4.1, the getValueAttribute() function was returning from

```
        if (! is_null($value)) {
            return $value;
        }
```

 I confirm that it's working passing the value withInput() like this:
`             return view('form.edit_step_by_step', $params)->withStep($next_step)`

But will I have to do this with all my custom hidden fields? Could you tell me how I will know which value I'll have to pass "withInput"?

Many thanks.

**Comment by drn5910** [comment]
Ah I see what's happening. These lines are now in the `getValueAttribute`: https://github.com/LaravelCollective/html/blob/v5.4.9/src/FormBuilder.php#L1161-L1164

This uses parameters from the current request, over the value supplied (which is generally preferable, because it allows pre-filling forms based on the request parameters without having to override the defaults if there are matching parameters in the request).

In this case, it would be best to use a plain HTML hidden input, as you don't need any of the benefits from the library (such as remembering previous values). Your input would simply be:

```
<input type="hidden" name="step" value="{{ $step }}"/>
```

As for the other hidden fields, I'm unsure what you're using them for so can't comment specifically. Generally if I don't need anything from the Form builder (such as value changes based on old input, current request etc.) then I would use plain HTML instead.

**Comment by smilearric** [comment]
> These lines are now in the `getValueAttribute`: https://github.com/LaravelCollective/html/blob/v5.4.9/src/FormBuilder.php#L1161-L1164

That's it. This is exactly where we're getting the value from now.

Thank you for your quick and clear answer @drn5910 (your name disappeared).

We found out that other hidden fields will not be concerned.

Best regards
