### ISSUE TITLE
Lumen compatibility

### ISSUE THREAD

**Issue by plakhin** [LaravelCollective/html#41]
This package can also be compatible with Lumen framework.

What I did to make it work:
1. removed "illuminate/routing": "~5.0", from composer.json (it is not required)
2. changed "use Illuminate\Routing\UrlGenerator;" to "use Laravel\Lumen\Routing\UrlGenerator;" in HtmlBuilder.php and FormBuilder.php
3. registered it with "$app->register('Collective\Html\HtmlServiceProvider');" in bootstrap/app.php
4. added facade bindings in bootstrap/app.php:
class_alias('Collective\Html\FormFacade', 'Form');
class_alias('Collective\Html\HtmlFacade', 'Html');

Seems to work fine.
It would be great to have compatibility with Lumen out of the box!

**Comment by jackmcdade** [comment]
Lumen's URLGenerator is missing some of the methods HTMLBuilder calls, like `asset()`, so that approach won't be perfect.

**Comment by adamgoose** [comment]
Thanks for the note Jack - that's exactly right. See here: https://github.com/LaravelCollective/docs/commit/0cf2342f5b3053c32b39fd3a71ec0ae260fb4d9c

**Comment by jackmcdade** [comment]
@adamgoose While i agree with that statement _in general_, I think that in this situation those "core changes to Lumen" would be beneficial and are not by themselves reason enough to use Laravel or Lumen. Those changes are simply 3 small helper methods to write asset paths, something an API could certainly take advantage of. 

In fact we're building [Statamic](http://statamic.com) 2.0 on Lumen because we literally don't need everything in Laravel. We don't need SwiftMailer, Eloquent, and a number of the other larger packages, and we need our own bootstrapping system. Lumen is _perfect_ for us. We need need some of these features though, so I'm sending a PR on Lumen for those methods.

Just my 2 cents.

**Comment by adamgoose** [comment]
@TaylorOtwell and I have already discussed this. He does not want to implement those helper methods.

**Comment by jackmcdade** [comment]
We had a chat and he changed his mind. It's fine if you don't want to support Lumen, but now you can if you want.

https://github.com/laravel/lumen-framework/pull/111

**Comment by adamgoose** [comment]
Well there you have it... We'll re-evaluate!

**Comment by RobinMalfait** [comment]
@adamgoose I will be more active once my exams are over!

@jackmcdade nice to see you here and in email :)

**Comment by edandy** [comment]
No found to {!! HTML:: !!}

**Comment by vluzrmos** [comment]
I made a fork to implement changes to work on Lumen:
https://github.com/vluzrmos/collective-html

**Comment by tshafer** [comment]
I am going to look into supporting lumen next week.

**Comment by tshafer** [comment]
If someone wants to make a pull request, feel free. I wont be implementing this anytime soon, no time.
