### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by armagedan** [LaravelCollective/html#600]
I just saw the website as I wanted to use this package again on a new project of mine. I just wanted to thank you for the package. This has been extremely helpful and I haven't used anything else since I have started using this package. I would love to see this package grow and evolve. Thank you for the countless hours spent on improving and fixing bug. Thank you for the patience you had with handling the issues. Thank you for making this project what it is today. Thank you Devs!

**Comment by ajcastro** [comment]
does this mean that we should not use laravelcollective/html anymore? 
I am planning to try this package and this would be my first time also.. but I saw the website that it will not be maintained anymore.

**Comment by armagedan** [comment]
No you can still use the package. If it is laravel 5.8 and below you’ll still be able to use it. As for docs, it’s pretty self explanatory tbh

**Comment by chriskonnertz** [comment]
> does this mean that we should not use laravelcollective/html anymore?
> I am planning to try this package and this would be my first time also.. but I saw the website that it will not be maintained anymore.

I think you misunderstand that. LaravelCollective/html **will be maintained**.

The website is down, because they "are currently starting development of a whole **new** website". Nothing to worry about.

The HTML repo has ~16000 Daily Downloads according to the website, so well, a lot of persons / projects are using it and there is no reason to drop support for this.

They said: "Annotations, Bus and Iron-queue, we will be shutting down their support", because barely someone is using them. This has nothing to do with the HTML repo!

**Comment by Erutan409** [comment]
@chriskonnertz So, the website is down...where is the documentation hosted for the time-being, then?

**Comment by armagedan** [comment]
@ajcastro Please refer to this for now

https://github.com/LaravelCollective/html/issues/587#issuecomment-497086556

This contains the google link to download html of the markdown of the docs way back in 2015 I think but it should be enough to get you started
