### ISSUE TITLE
Mutiple radio same id

### ISSUE THREAD

**Issue by thetispro** [LaravelCollective/html#94]
Form::radio('foo', '1');
Form::radio('foo', '2');

Html =>
`<input name="foo" type="radio" value='1" id="foo">`
`<input name="foo" type="radio" value='2" id="foo">`

Why must add an "id"? In addition, the "id" must be unique…

**Comment by tshafer** [comment]
We accept pull requests.

**Comment by marcusmoore88** [comment]
I can work on this but I would like to know what you would expect to happen if a user uses the code above:  
```
Form::radio('foo', '1');
Form::radio('foo', '2');
```

Some kind of a warning letting the developer know that id must be unique? Get crazy and throw an exception?

**Comment by ZhangYiJiang** [comment]
@marcusmoore88 

The problem is that the function expects `name` = `id`, which is okay for most form elements, but not radio buttons. Radio buttons work **because** they all have the same `name`, but must not have the same `id` if you want to connect them to `label` elements. Most developers write 

    <label><input type='radio' [...] /> Label for this option</label>

thus obviating the need for the `input` element to have an `id` anyway. 

Two Proposals: 

1. Drop the automatically generated `id`. This will force developers to add in `id` through the `options` parameter.
2. Append the `value` of the radiobutton to the given `name` to generate a unique `id` for each radio button. 

Both will likely break existing HTML generated with this function, but then again the existing HTML generated is already broken.

**Comment by arthurkirkosa** [comment]
A combination of the two will satisfy most people. Have a default and have the option to overwrite it.

**Comment by ZhangYiJiang** [comment]
I noticed that if you pass in an `id` over the `options` parameter, the function will prefer that to the one it tries to generate. So for now I'm passing `['id' => NULL]` as the fourth parameter. It's not ideal - the function shouldn't be generating broken HTML by default, but it works well enough.

**Comment by adamgoose** [comment]
The simplist solution here, for the time being, is to *not* use the `Form::label()` method for this particular checkbox. Since it's simply an HTML helper, try using raw HTML `<label>` tags, and the form builder will not add the ID to the element.

**Comment by cotiga** [comment]
If that helps, because I have been looking for a while before finding
```
{{ Form::radio('name', 'M.', true, ['class' => 'form-check-input', 'id' => 'id_man']) }}
{{ Form::label('id_man', 'M.', ['class' => 'form-check-label']) }}

{{ Form::radio('name', 'Mme', '', ['class' => 'form-check-input', 'id' => 'id_female']) }}
{{ Form::label('id_female', 'Mme', ['class' => 'form-check-label']) }}

```
On the Radio Input, before the options array, add an empty option '' or 'true' for selecting by default.
Work on V 5.7 and 6
